# Generated by Django 5.1.5 on 2026-08-01 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("path", models.CharField(db_index=True, max_length=500)),
                (
                    "project_slug",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("status", models.PositiveSmallIntegerField(default=200)),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=400)),
                ("referer", models.CharField(blank=True, max_length=500)),
                ("is_bot", models.BooleanField(db_index=True, default=False)),
                (
                    "visitor_hash",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at", "is_bot"],
                        name="portfolio_p_created_11bafc_idx",
                    )
                ],
            },
        ),
    ]
