# Generated by Django 5.1.5 on 2026-09-18 17:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KittenProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Mais", max_length=100)),
                ("slug", models.SlugField(default="mais", max_length=100, unique=True)),
                (
                    "tagline",
                    models.CharField(
                        default="Femmina · 7 settimane · Piccola panterina nera",
                        max_length=200,
                    ),
                ),
                (
                    "age_text",
                    models.CharField(default="7 settimane circa", max_length=50),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("Femmina", "Femmina ♀"), ("Maschio", "Maschio ♂")],
                        default="Femmina",
                        max_length=20,
                    ),
                ),
                (
                    "color",
                    models.CharField(default="Completamente nera", max_length=100),
                ),
                (
                    "location",
                    models.CharField(
                        default="Pescara (zona Aeroporto) e dintorni", max_length=150
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Numero di telefono per chiamate e WhatsApp (es. 340 1234567)",
                        max_length=50,
                    ),
                ),
                (
                    "whatsapp_number",
                    models.CharField(
                        blank=True,
                        help_text="Opzionale: lascialo vuoto se è uguale al numero sopra",
                        max_length=50,
                    ),
                ),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                (
                    "contact_notes",
                    models.CharField(
                        blank=True,
                        default="Contattami via WhatsApp o chiamata per conoscerla di persona!",
                        max_length=250,
                    ),
                ),
                (
                    "bio_intro",
                    models.TextField(
                        default="Mi chiamo Mais! Da dove viene il mio nome? Da mice(tto) ➔ mice (topolino in inglese) ➔ pronunciato all'italiana: MAIS! 🌽\nSono una gattina completamente nera di circa 7 settimane, una vera panterina in miniatura. Sono curiosa del mondo, dolcissima e con una gran voglia di trovare la mia famiglia per sempre."
                    ),
                ),
                (
                    "personality",
                    models.TextField(
                        default="Sono un vulcano di allegria e affetto: adoro inseguire palline, fare agguati giocosi e appena mi prendi in braccio accendo il motore delle fusa a tutto volume! Amo stare con le persone e condividere ogni momento."
                    ),
                ),
                (
                    "health_info",
                    models.TextField(
                        default="• Prima visita veterinaria eseguita con successo 🩺\n• Prima sverminazione effettuata\n• Da completare: piano vaccinale, sverminazione totale e futura sterilizzazione (requisito per l'adozione)\n• Mangia con appetito la pappa umida 🐟\n• È bravissima ed educata: usa regolarmente la lettiera! 🚽"
                    ),
                ),
                (
                    "adoption_requirements",
                    models.TextField(
                        default="Cerchiamo per Mais un'adozione d'amore e consapevole:\n• Casa sicura (protezione a finestre e balconi)\n• Impegno a completare vaccini e sterilizzazione in età opportuna\n• Disponibilità a breve colloquio conoscitivo pre-affido (Pescara e province limitrofe)\n• Mais è una compagna per la vita, non un giocattolo!"
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="kitten/covers/"
                    ),
                ),
                (
                    "is_adopted",
                    models.BooleanField(
                        default=False, verbose_name="Gattina adottata! 🎉"
                    ),
                ),
                ("likes_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Profilo Gattino",
                "verbose_name_plural": "Profili Gattini",
            },
        ),
        migrations.CreateModel(
            name="KittenPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=150)),
                ("caption", models.TextField(blank=True)),
                (
                    "tag",
                    models.CharField(
                        choices=[
                            ("gioco", "Attacco Giocherellone 🎾"),
                            ("pappa", "Momento Pappa 🐟"),
                            ("coccole", "Fusa e Coccole 💖"),
                            ("nanna", "Pisolo Strategico 💤"),
                            ("scoperte", "Piccole Scoperte 🐾"),
                            ("visita", "Visita Veterinaria 🩺"),
                            ("altro", "Momento Dolce ✨"),
                        ],
                        default="gioco",
                        max_length=30,
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("photo", "Foto"),
                            ("video", "Video"),
                            ("text", "Solo Testo"),
                        ],
                        default="photo",
                        max_length=10,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="kitten/posts/images/"
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True, null=True, upload_to="kitten/posts/videos/"
                    ),
                ),
                (
                    "video_poster",
                    models.ImageField(
                        blank=True, null=True, upload_to="kitten/posts/posters/"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_featured", models.BooleanField(default=False)),
                ("likes", models.PositiveIntegerField(default=0)),
                (
                    "kitten",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="kitten.kittenprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Post del Feed",
                "verbose_name_plural": "Post del Feed",
                "ordering": ["-created_at"],
            },
        ),
    ]
