# Generated by Django 5.1.5 on 2026-09-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitten", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="kittenprofile",
            name="adopted_banner_text",
            field=models.CharField(
                blank=True,
                default="🎉 MERAVIGLIOSA NOTIZIA! Mais ha trovato la sua famiglia per sempre! Grazie a tutti per l'affetto! ❤️",
                max_length=250,
            ),
        ),
        migrations.AddField(
            model_name="kittenprofile",
            name="adoption_badge",
            field=models.CharField(
                blank=True, default="🏡 Amore Consapevole", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="kittenprofile",
            name="adoption_cta_desc",
            field=models.TextField(
                blank=True,
                default="Siamo a Pescara (zona Aeroporto). Scrivici su WhatsApp o chiamaci per fare due chiacchiere senza impegno e organizzare un incontro!",
            ),
        ),
        migrations.AddField(
            model_name="kittenprofile",
            name="adoption_cta_title",
            field=models.CharField(
                blank=True,
                default="Vuoi venire a conoscere Mais di persona?",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="kittenprofile",
            name="adoption_intro",
            field=models.TextField(
                blank=True,
                default="Mais è un esserino vivace che merita una vita serena e protetta. Cerchiamo persone speciali che la amino come una di famiglia:",
            ),
        ),
        migrations.AddField(
            model_name="kittenprofile",
            name="adoption_title",
            field=models.CharField(
                blank=True, default="Requisiti per l'adozione", max_length=150
            ),
        ),
        migrations.AddField(
            model_name="kittenprofile",
            name="bullet_1",
            field=models.CharField(
                blank=True,
                default="Super Giocherellona: adora rincorrere palline, cordini e fare piccoli agguati comici",
                max_length=250,
            ),
        ),
        migrations.AddField(
            model_name="kittenprofile",
            name="bullet_2",
            field=models.CharField(
                blank=True,
                default="Buongustaia: mangia con grande gioia la sua pappa umida 🐟",
                max_length=250,
            ),
        ),
        migrations.AddField(
            model_name="kittenprofile",
            name="bullet_3",
            field=models.CharField(
                blank=True,
                default="Educatissima: usa già la lettiera in modo impeccabile 🚽",
                max_length=250,
            ),
        ),
        migrations.AddField(
            model_name="kittenprofile",
            name="bullet_4",
            field=models.CharField(
                blank=True,
                default="Regina delle Fusa: basta una carezza sotto il mento per sentirla vibrare!",
                max_length=250,
            ),
        ),
        migrations.AddField(
            model_name="kittenprofile",
            name="feed_empty_desc",
            field=models.TextField(
                blank=True,
                default="Mais sta facendo un sonnellino dopo aver mangiato la pappa umida. I primi video e le foto delle sue avventure verranno caricati a breve!",
            ),
        ),
        migrations.AddField(
            model_name="kittenprofile",
            name="feed_empty_title",
            field=models.CharField(
                blank=True, default="Il diario fotografico è in arrivo!", max_length=150
            ),
        ),
        migrations.AddField(
            model_name="kittenprofile",
            name="feed_subtitle",
            field=models.CharField(
                blank=True,
                default="Scatti spontanei, video buffi e momenti quotidiani",
                max_length=250,
            ),
        ),
        migrations.AddField(
            model_name="kittenprofile",
            name="feed_title",
            field=models.CharField(
                blank=True, default="Il Diario di Mais 📸", max_length=150
            ),
        ),
        migrations.AddField(
            model_name="kittenprofile",
            name="flyer_contact_label",
            field=models.CharField(
                blank=True, default="Per informazioni e per conoscerla:", max_length=150
            ),
        ),
        migrations.AddField(
            model_name="kittenprofile",
            name="flyer_cta_sub",
            field=models.CharField(
                blank=True,
                default="Guarda i video mentre gioca, tutte le foto e la sua storia completa su:",
                max_length=250,
            ),
        ),
        migrations.AddField(
            model_name="kittenprofile",
            name="flyer_cta_text",
            field=models.CharField(
                blank=True, default="📲 Inquadra il QR con il telefono!", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="kittenprofile",
            name="flyer_header_badge",
            field=models.CharField(
                blank=True, default="❤️ ADOZIONE DEL CUORE ❤️", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="kittenprofile",
            name="flyer_subtitle",
            field=models.CharField(
                blank=True,
                default="Piccola panterina nera in cerca di una casa felice",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="kittenprofile",
            name="flyer_title",
            field=models.CharField(
                blank=True, default="CERCASI FAMIGLIA PER SEMPRE! 🐾", max_length=150
            ),
        ),
        migrations.AddField(
            model_name="kittenprofile",
            name="health_step1_badge",
            field=models.CharField(blank=True, default="Fatto ✓", max_length=50),
        ),
        migrations.AddField(
            model_name="kittenprofile",
            name="health_step1_desc",
            field=models.TextField(
                blank=True,
                default="Visita generale superata a pieni voti: vispa, reattiva e in ottima salute generale.",
            ),
        ),
        migrations.AddField(
            model_name="kittenprofile",
            name="health_step1_done",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="kittenprofile",
            name="health_step1_title",
            field=models.CharField(
                blank=True, default="Prima Visita Veterinaria", max_length=150
            ),
        ),
        migrations.AddField(
            model_name="kittenprofile",
            name="health_step2_badge",
            field=models.CharField(blank=True, default="Fatto ✓", max_length=50),
        ),
        migrations.AddField(
            model_name="kittenprofile",
            name="health_step2_desc",
            field=models.TextField(
                blank=True,
                default="Trattamento parassitario iniziale effettuato regolarmente.",
            ),
        ),
        migrations.AddField(
            model_name="kittenprofile",
            name="health_step2_done",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="kittenprofile",
            name="health_step2_title",
            field=models.CharField(
                blank=True, default="Prima Sverminazione", max_length=150
            ),
        ),
        migrations.AddField(
            model_name="kittenprofile",
            name="health_step3_badge",
            field=models.CharField(blank=True, default="Da completare", max_length=50),
        ),
        migrations.AddField(
            model_name="kittenprofile",
            name="health_step3_desc",
            field=models.TextField(
                blank=True,
                default="Da effettuare a breve dal veterinario di fiducia della nuova famiglia.",
            ),
        ),
        migrations.AddField(
            model_name="kittenprofile",
            name="health_step3_done",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="kittenprofile",
            name="health_step3_title",
            field=models.CharField(
                blank=True, default="Vaccini & Sverminazione Completa", max_length=150
            ),
        ),
        migrations.AddField(
            model_name="kittenprofile",
            name="health_step4_badge",
            field=models.CharField(
                blank=True, default="Futuro (obbligo)", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="kittenprofile",
            name="health_step4_desc",
            field=models.TextField(
                blank=True,
                default="Da effettuare al raggiungimento dell'età idonea (circa 6 mesi) per il suo benessere.",
            ),
        ),
        migrations.AddField(
            model_name="kittenprofile",
            name="health_step4_done",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="kittenprofile",
            name="health_step4_title",
            field=models.CharField(
                blank=True, default="Sterilizzazione", max_length=150
            ),
        ),
        migrations.AddField(
            model_name="kittenprofile",
            name="health_subtitle",
            field=models.CharField(
                blank=True,
                default="Trasparenza totale per chi deciderà di accoglierla",
                max_length=250,
            ),
        ),
        migrations.AddField(
            model_name="kittenprofile",
            name="health_title",
            field=models.CharField(
                blank=True, default="Stato di Salute & Visite", max_length=150
            ),
        ),
        migrations.AddField(
            model_name="kittenprofile",
            name="hero_badge",
            field=models.CharField(
                blank=True,
                default="🐾 In cerca di una famiglia d'amore",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="kittenprofile",
            name="hero_location_badge",
            field=models.CharField(
                blank=True, default="Zona Aeroporto · Pescara", max_length=150
            ),
        ),
        migrations.AddField(
            model_name="kittenprofile",
            name="hero_title",
            field=models.CharField(
                blank=True, default="Ciao, mi chiamo Mais! 🐾", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="kittenprofile",
            name="personality_icon",
            field=models.CharField(blank=True, default="⚡", max_length=20),
        ),
        migrations.AddField(
            model_name="kittenprofile",
            name="personality_title",
            field=models.CharField(
                blank=True, default="Carattere e Superpoteri", max_length=150
            ),
        ),
        migrations.AddField(
            model_name="kittenprofile",
            name="spec_age",
            field=models.CharField(
                blank=True, default="7 settimane circa", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="kittenprofile",
            name="spec_color",
            field=models.CharField(
                blank=True, default="Nero splendente", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="kittenprofile",
            name="spec_gender",
            field=models.CharField(blank=True, default="Femmina", max_length=50),
        ),
        migrations.AddField(
            model_name="kittenprofile",
            name="spec_location",
            field=models.CharField(
                blank=True, default="Pescara (Aeroporto)", max_length=150
            ),
        ),
        migrations.AddField(
            model_name="kittenprofile",
            name="story_icon",
            field=models.CharField(blank=True, default="🌽", max_length=20),
        ),
        migrations.AddField(
            model_name="kittenprofile",
            name="story_quote",
            field=models.TextField(
                blank=True,
                default="«Non lasciatevi ingannare dal mantello scuro: non porto sfortuna, porto solo una quantità infinita di amore, risate e fusa calde!»",
            ),
        ),
        migrations.AddField(
            model_name="kittenprofile",
            name="story_title",
            field=models.CharField(
                blank=True, default="Perché mi chiamo Mais?", max_length=150
            ),
        ),
        migrations.AddField(
            model_name="kittenprofile",
            name="whatsapp_message",
            field=models.CharField(
                blank=True,
                default="Ciao! Ho visto Mais su labustagialla.it e vorrei avere informazioni per conoscerla e adottarla! 🐾",
                max_length=250,
            ),
        ),
        migrations.AlterField(
            model_name="kittenprofile",
            name="adoption_requirements",
            field=models.TextField(
                blank=True,
                default="Cerchiamo per Mais un'adozione d'amore e consapevole:\n• Casa sicura (protezione a finestre e balconi)\n• Impegno a completare vaccini e sterilizzazione in età opportuna\n• Disponibilità a breve colloquio conoscitivo pre-affido (Pescara e province limitrofe)\n• Mais è una compagna per la vita, non un giocattolo!",
            ),
        ),
        migrations.AlterField(
            model_name="kittenprofile",
            name="age_text",
            field=models.CharField(
                blank=True, default="7 settimane circa", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="kittenprofile",
            name="bio_intro",
            field=models.TextField(
                blank=True,
                default="Mi chiamo Mais! Da dove viene il mio nome? Da mice(tto) ➔ mice (topolino in inglese) ➔ pronunciato all'italiana: MAIS! 🌽\nSono una gattina completamente nera di circa 7 settimane, una vera panterina in miniatura. Sono curiosa del mondo, dolcissima e con una gran voglia di trovare la mia famiglia per sempre.",
            ),
        ),
        migrations.AlterField(
            model_name="kittenprofile",
            name="color",
            field=models.CharField(
                blank=True, default="Completamente nera", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="kittenprofile",
            name="health_info",
            field=models.TextField(
                blank=True,
                default="• Prima visita veterinaria eseguita con successo 🩺\n• Prima sverminazione effettuata\n• Da completare: piano vaccinale, sverminazione totale e futura sterilizzazione (requisito per l'adozione)\n• Mangia con appetito la pappa umida 🐟\n• È bravissima ed educata: usa regolarmente la lettiera! 🚽",
            ),
        ),
        migrations.AlterField(
            model_name="kittenprofile",
            name="location",
            field=models.CharField(
                blank=True,
                default="Pescara (zona Aeroporto) e dintorni",
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="kittenprofile",
            name="personality",
            field=models.TextField(
                blank=True,
                default="Sono un vulcano di allegria e affetto: adoro inseguire palline, fare agguati giocosi e appena mi prendi in braccio accendo il motore delle fusa a tutto volume! Amo stare con le persone e condividere ogni momento.",
            ),
        ),
        migrations.AlterField(
            model_name="kittenprofile",
            name="tagline",
            field=models.CharField(
                blank=True,
                default="Femmina · 7 settimane · Piccola panterina nera",
                max_length=200,
            ),
        ),
    ]
