# Generated by Django 5.1.5 on 2026-09-18 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitten", "0002_kittenprofile_adopted_banner_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="kittenprofile",
            name="telegram_bot_token",
            field=models.CharField(
                blank=True,
                help_text="Token del bot Telegram (da @BotFather)",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="kittenprofile",
            name="telegram_chat_id",
            field=models.CharField(
                blank=True, help_text="ID della chat o gruppo Telegram", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="kittenprofile",
            name="telegram_notifications_enabled",
            field=models.BooleanField(
                default=True, verbose_name="Notifiche Telegram attive"
            ),
        ),
        migrations.CreateModel(
            name="KittenInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inquiry_token",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "contact",
                    models.CharField(
                        help_text="Telefono, WhatsApp o Email", max_length=150
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Nuovo 🟡"),
                            ("replied", "Risposto 🟢"),
                            ("closed", "Chiuso ⚪"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kitten",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inquiries",
                        to="kitten.kittenprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Richiesta di Adozione / Chat",
                "verbose_name_plural": "Richieste di Adozione / Chat",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="KittenInquiryMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender",
                    models.CharField(
                        choices=[("visitor", "Adottante"), ("admin", "Staff")],
                        default="visitor",
                        max_length=10,
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inquiry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="kitten.kitteninquiry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Messaggio Chat",
                "verbose_name_plural": "Messaggi Chat",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="KittenVisitorSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("visitor_hash", models.CharField(blank=True, max_length=64)),
                ("ip_address", models.CharField(blank=True, max_length=64, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=400)),
                ("device_type", models.CharField(default="mobile", max_length=20)),
                ("referer", models.CharField(blank=True, max_length=500)),
                ("utm_source", models.CharField(blank=True, max_length=100)),
                ("total_seconds", models.PositiveIntegerField(default=0)),
                ("max_scroll_percent", models.PositiveIntegerField(default=0)),
                ("reached_feed", models.BooleanField(default=False)),
                ("reached_adoption", models.BooleanField(default=False)),
                ("clicked_whatsapp", models.BooleanField(default=False)),
                ("clicked_call", models.BooleanField(default=False)),
                ("clicked_chat", models.BooleanField(default=False)),
                ("likes_given", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kitten",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visitor_sessions",
                        to="kitten.kittenprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sessione Visitatore",
                "verbose_name_plural": "Sessioni Visitatori",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="KittenPostImpression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impressions",
                        to="kitten.kittenpost",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impressions",
                        to="kitten.kittenvisitorsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Visualizzazione Post",
                "verbose_name_plural": "Visualizzazioni Post",
                "ordering": ["-created_at"],
                "unique_together": {("session", "post")},
            },
        ),
    ]
