# Generated by Django 5.1.5 on 2026-09-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitten", "0003_kittenprofile_telegram_bot_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kittenprofile",
            name="bullet_2",
            field=models.CharField(
                blank=True,
                default="Buongustaia: mangia con grande gioia la sua pappa umida, sopratutto al salmone",
                max_length=250,
            ),
        ),
        migrations.AlterField(
            model_name="kittenprofile",
            name="health_step1_desc",
            field=models.TextField(blank=True, default="Vispa, reattiva e in salute"),
        ),
    ]
