# Generated by Django 5.1.5 on 2026-09-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitten", "0004_alter_kittenprofile_bullet_2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kittenprofile",
            name="bullet_3",
            field=models.CharField(
                blank=True,
                default="Educatissima: usa già la lettiera in modo impeccabile",
                max_length=250,
            ),
        ),
    ]
